### ISSUE TITLE
README contains out-of-date instructions

### ISSUE THREAD

**Issue by InterferencePattern** [dhanani94/mbta_predictions#11]
Currently the README uses the (possibly outdated) `stop` and `destination` fields instead of `depart_from` and `arrive_at`.
```
  - platform: mbta_predictions
    predictions:
      - stop: STOP_NAME
        destination: DESTINATION_NAME
        route: ROUTE_NAME
```
